version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - cyclop
    - dupl
    - forbidigo
    - gochecknoglobals
    - gocognit
    - goconst
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - whitespace
  settings:
    cyclop:
      max-complexity: 10
    errcheck:
      check-type-assertions: true
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - prealloc
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
